### ISSUE TITLE
Invalid key constant when pressing space in debug console

### ISSUE THREAD

**Issue by serpent7776** [Ranguna/LOVEDEBUG#22]
I got error when I type space key while debug console is visible.
This is because here: https://github.com/Ranguna/LOVEDEBUG/blob/43efb8232c24bd7bed7e13f4e0850f2d7dc30199/lovedebug.lua#L723
the `key` is properly set to `"space"` and this is handled properly, but then at the same place `key` has value `" "`, which is set from here https://github.com/Ranguna/LOVEDEBUG/blob/43efb8232c24bd7bed7e13f4e0850f2d7dc30199/lovedebug.lua#L682
and this causes the error

My love version is
`LOVE 11.3 (Mysterious Mysteries)`

```
Error

lib/lovedebug.lua:723: Invalid key constant:  


Traceback

[C]: in function 'isDown'
lib/lovedebug.lua:723: in function <lib/lovedebug.lua:647>
[C]: in function 'xpcall'
[C]: in function 'xpcall'
```

**Comment by maxiy01** [comment]
Check [this](https://github.com/flamendless/lovedebug) repo.

**Comment by serpent7776** [comment]
Thanks, that repo works fine.

**Comment by Ranguna** [comment]
Thanks @maxiy01.
Closing issue.
