### ISSUE TITLE
Console does not auto refresh when open. Love2d 0.9.1

### ISSUE THREAD

**Issue by admin36** [Ranguna/LOVEDEBUG#3]
Awesome project!!!

Issue:

When you have the lovedebug console open and your program is issuing print() calls the console does not update with the new print call strings. You must close and re-open the console for the print calls to show.

**Comment by Ranguna** [comment]
I'm going to look into this.

**Comment by Ranguna** [comment]
Where  is your program calling the  print statements ? 
When the console is on, love's update and draw functions are halted so it's natural that print functions stop getting called.

**Comment by admin36** [comment]
So here is a minimal example below. A timer is setup to call a print statement every second. As you mentioned it does appear that lovedebug halts program execution when the console is open, thus I have to close and re-open the console to see my print statements show.

```lua
require('lovedebug')

timer = 0

function love.load()    
end

function love.update(DT)
    if timer >= 1 then
        print(os.clock())
        timer = 0
    end
    
    timer = timer + 1 * DT
end

function love.draw() 
    love.graphics.print(timer, love.graphics.getWidth()/2, love.graphics.getHeight()/2)    
end
```
Is there any way to allow lovedebug to not halt program execution ( a setting maybe)? I wish to use lovedebug to print data to console while my game is running live.

Thanks again!

**Comment by admin36** [comment]
So I took a quick stab at the code, it looks like if I add a single line to the bottom of the code block where it checks if the _Debug.drawOverlay is true it will continue to call the standard love update/draw methods. 

I've forked and committed the adjustment I'm talking about here:

https://github.com/admin36/LOVEDEBUG/commit/1a3964015e7bb3b4ce00f5ff1350500039cc0cff

This is obviously not safe until I have input from you that this will not break anything. In addition, it would be nice to toggle halting program execution or not.

Thoughts?

**Comment by admin36** [comment]
I've generated a pull request that adds two new settings:

HaltExecution: setting to control if love.update() is halted when console is open
AutoScroll: setting to control if the console window is auto scrolled once the console is full

Please review the following pull request and let me know if any issues:

https://github.com/Ranguna/LOVEDEBUG/pull/6

**Comment by Ranguna** [comment]
Your changes are totally safe and that's actually a nice addition, I don't know why I never coded that myself :cool: 
I'll merge your code.
